sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: root
  alioss:
    bucket-name:
    endpoint:
    access-key-id:
    access-key-secret:
  redis:
    host: localhost
    port: 6379
    password: root
    database: 0
  wechat:
    appid:
    secret: